=== Azimkhan/XMLWeb/src/main/webapp/WEB-INF/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://epam.com/goods"
	xmlns:tns="http://epam.com/goods" elementFormDefault="qualified">

	<element name="categories">
		<complexType>
			<sequence>
				<element name="category" type="tns:Category" maxOccurs="unbounded"
					minOccurs="1" />
			</sequence>
		</complexType>
	</element>

	<!-- category definition -->
	<complexType name="Category">
		<sequence>
			<element name="subcategory" type="tns:SubCategory" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" use="required" />

	</complexType>

	<!-- subcategory definition -->
	<complexType name="SubCategory">
		<sequence>
			<element name="goods" type="tns:Goods" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>

	<!-- goods definition -->
	<complexType name="Goods">
		<sequence>

			<!-- producer -->
			<element name="producer" type="string" />

			<!-- model -->
			<element name="model">
				<simpleType>
					<restriction base="string">
						<pattern value="[A-Z]{2}[0-9]{3}" />
					</restriction>
				</simpleType>
			</element>

			<!-- date -->
			<element name="date" type="date" />

			<!-- color -->
			<element name="color">
				<simpleType>
					<restriction base="string">
						<enumeration value="Red" />
						<enumeration value="Black" />
						<enumeration value="White" />
						<enumeration value="red" />
						<enumeration value="black" />
						<enumeration value="white" />
					</restriction>
				</simpleType>
			</element>

			<!-- a choice between price and notInStock -->
			<choice>
				<!-- price definition -->
				<element name="price" type="positiveInteger" />

				<!-- notInStock definition -->
				<element name="notInStock">
					<simpleType>
						<restriction base="string">
							<!-- only 1 possible value in this case -->
							<enumeration value="true" />
						</restriction>
					</simpleType>
				</element>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
</schema>

=== Azimkhan/XMLWeb/src/main/webapp/WEB-INF/goods.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<categories xmlns="http://epam.com/goods" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://epam.com/goods schema.xsd">
	<category name="Electronics">
		<subcategory name="Smartphones">

			<goods name="Apple iPhone 5s">
				<producer>Apple</producer>
				<model>IP501</model>
				<date>2012-09-09</date>
				<color>White</color>
				<price>880</price>
			</goods>

			<goods name="Samsung Galaxy Ace II">
				<producer>Samsung</producer>
				<model>GT160</model>
				<date>2012-04-04</date>
				<color>Black</color>
				<price>234</price>
			</goods>

			<goods name="Apple iPhone 5c">
				<producer>Apple</producer>
				<model>IP508</model>
				<date>2013-09-09</date>
				<color>Red</color>
				<price>934</price>
			</goods>


			<goods name="Nokia Lumia 1520">
				<producer>Nokia</producer>
				<model>LM152</model>
				<date>2013-09-09</date>
				<color>black</color>
				<price>990</price>
			</goods>

			<goods name="Nokia Lumia 1320">
				<producer>Nokia</producer>
				<model>LM132</model>
				<date>2013-09-09</date>
				<color>black</color>
				<price>890</price>
			</goods>
		</subcategory>

		<subcategory name="Notebooks">

			<goods name="Apple MacBook Air ">
				<producer>Apple</producer>
				<model>MD223</model>
				<date>2012-07-10</date>
				<color>black</color>
				<price>1200</price>
			</goods>
			
			<goods name="Apple MacBook Air ">
				<producer>Apple</producer>
				<model>MD711</model>
				<date>2012-07-10</date>
				<color>black</color>
				<price>1340</price>
			</goods>
			
			<goods name="Apple MacBook Air ">
				<producer>Apple</producer>
				<model>MD712</model>
				<date>2012-07-10</date>
				<color>black</color>
				<price>1800</price>
			</goods>
			
			<goods name="HP Pavilion g6">
				<producer>Hewlett-Packard</producer>
				<model>HP001</model>
				<date>2011-09-01</date>
				<color>White</color>
				<notInStock>true</notInStock>
			</goods>
			
			<goods name="Ноутбук HP ENVY TouchSmart 15-j026sr ">
				<producer>Hewlett-Packard</producer>
				<model>HP002</model>
				<date>2013-09-09</date>
				<color>black</color>
				<price>1743</price>
			</goods>
		</subcategory>
	</category>

	<category name="Books">
		<subcategory name="Computers and Programming">
			<goods name="Java. Методы программирования.">
				<producer>И.Н. Блинов, В.С. Романчик</producer>
				<model>VE001</model>
				<date>2013-08-08</date>
				<color>White</color>
				<notInStock>true</notInStock>
			</goods>

			<goods name="The Well-Grounded Rubyist">
				<producer>David A. Black</producer>
				<model>WG004</model>
				<date>2009-07-04</date>
				<color>Black</color>
				<price>31</price>
			</goods>
			
			<goods name="Programming Python, 4th Edition">
				<producer>Mark Lutz</producer>
				<model>PP004</model>
				<date>2010-12-01</date>
				<color>White</color>
				<price>52</price>
			</goods>
		</subcategory>
	</category>
<category name="test">
    <subcategory name="test">
      <goods name="adsf AA001">
        <producer>adsf</producer>
        <model>AA001</model>
        <date>2012-09-12</date>
        <color>white</color>
        <price>123</price>
      </goods>
    </subcategory>
  </category>
</categories>
